# Define the text
$text = @"
"TaskName","TaskPath","Description","State","Actions","Arguments"
"CreateExplorerShellUnelevatedTask","\",,"Running","C:\Windows\Explorer.EXE","/NOUACCHECK"
"User_Feed_Synchronization-{626A69CF-A127-4E17-92B6-17A23BB6D456}","\","Updates out-of-date system feeds.","Ready","C:\Windows\system32\msfeedssync.exe","sync"
".NET Framework NGEN v4.0.30319","\Microsoft\Windows\.NET Framework\",,"Ready","",""
".NET Framework NGEN v4.0.30319 64","\Microsoft\Windows\.NET Framework\",,"Ready","",""
".NET Framework NGEN v4.0.30319 64 Critical","\Microsoft\Windows\.NET Framework\",,"Disabled","",""
".NET Framework NGEN v4.0.30319 Critical","\Microsoft\Windows\.NET Framework\",,"Disabled","",""
"AD RMS Rights Policy Template Management (Automated)","\Microsoft\Windows\Active Directory Rights Management Services Client\","Updates the AD RMS rights policy templates for the user. This job does not provide a credential prompt if authentication to the template distribution web service on the server fails. In this case, it fails silently.","Disabled","",""
"AD RMS Rights Policy Template Management (Manual)","\Microsoft\Windows\Active Directory Rights Management Services Client\","Updates the AD RMS rights policy templates for the user. This job provides a credential prompt if authentication to the template distribution web service on the server fails.","Ready","",""
"EDP Policy Manager","\Microsoft\Windows\AppID\","This task performs steps necessary to configure Windows Information Protection.","Ready","",""
"PolicyConverter","\Microsoft\Windows\AppID\","Converts the software restriction policies policy from XML into binary format.","Disabled","%windir%\system32\appidpolicyconverter.exe",""
"VerifiedPublisherCertStoreCheck","\Microsoft\Windows\AppID\","Inspects the AppID certificate cache for invalid or revoked certificates.","Disabled","%windir%\system32\appidcertstorecheck.exe",""
"Microsoft Compatibility Appraiser","\Microsoft\Windows\Application Experience\","Collects program telemetry information if opted-in to the Microsoft Customer Experience Improvement Program.","Ready","%windir%\system32\compattelrunner.exe",""
"ProgramDataUpdater","\Microsoft\Windows\Application Experience\","$(@%SystemRoot%\system32\invagent.dll,-702)","Ready","%windir%\system32\compattelrunner.exe","-maintenance"
"StartupAppTask","\Microsoft\Windows\Application Experience\","Scans startup entries and raises notification to the user if there are too many startup entries.","Ready","%windir%\system32\rundll32.exe","Startupscan.dll,SusRunTask"
"appuriverifierdaily","\Microsoft\Windows\ApplicationData\","Verifies AppUriHandler host registrations.","Ready","%windir%\system32\AppHostRegistrationVerifier.exe",""
"appuriverifierinstall","\Microsoft\Windows\ApplicationData\","Verifies AppUriHandler host registrations.","Ready","%windir%\system32\AppHostRegistrationVerifier.exe",""
"CleanupTemporaryState","\Microsoft\Windows\ApplicationData\","Cleans up each package's unused temporary files.","Ready","%windir%\system32\rundll32.exe","Windows.Storage.ApplicationData.dll,CleanupTemporaryState"
"DsSvcCleanup","\Microsoft\Windows\ApplicationData\","Performs maintenance for the Data Sharing Service.","Ready","%windir%\system32\dstokenclean.exe",""
"Pre-staged app cleanup","\Microsoft\Windows\AppxDeploymentClient\",,"Disabled","%windir%\system32\rundll32.exe","%windir%\system32\AppxDeploymentClient.dll,AppxPreStageCleanupRunTask"
"Proxy","\Microsoft\Windows\Autochk\","This task collects and uploads autochk SQM data if opted-in to the Microsoft Customer Experience Improvement Program.","Ready","%windir%\system32\rundll32.exe","/d acproxy.dll,PerformAutochkOperations"
"BitLocker Encrypt All Drives","\Microsoft\Windows\BitLocker\",,"Ready","",""
"BitLocker MDM policy Refresh","\Microsoft\Windows\BitLocker\",,"Ready","",""
"UninstallDeviceTask","\Microsoft\Windows\Bluetooth\","Uninstalls the PnP device associated with the specified Bluetooth service ID","Ready","BthUdTask.exe","$(Arg0)"
"BgTaskRegistrationMaintenanceTask","\Microsoft\Windows\BrokerInfrastructure\","Maintains registrations for background tasks for Universal Windows Platform applications.","Ready","",""
"AikCertEnrollTask","\Microsoft\Windows\CertificateServicesClient\","This task enrolls a certificate for Attestation Identity Key.","Ready","",""
"CryptoPolicyTask","\Microsoft\Windows\CertificateServicesClient\","This task synchronizes cryptographic policy.","Ready","",""
"KeyPreGenTask","\Microsoft\Windows\CertificateServicesClient\","This task pre-generates TPM based Attestation Identity Key (AIK) and Storage Key (SK).","Ready","",""
"SystemTask","\Microsoft\Windows\CertificateServicesClient\","Certificate Services Client automatically manages digital identities such as Certificates, Keys and Credentials for the users and the machine, enabling enrollment, roaming and other services.","Ready","",""
"UserTask","\Microsoft\Windows\CertificateServicesClient\","Certificate Services Client automatically manages digital identities such as Certificates, Keys and Credentials for the users and the machine, enabling enrollment, roaming and other services.","Ready","",""
"UserTask-Roam","\Microsoft\Windows\CertificateServicesClient\","Certificate Services Client automatically manages digital identities such as Certificates, Keys and Credentials for the users and the machine, enabling enrollment, roaming and other services.","Ready","",""
"ProactiveScan","\Microsoft\Windows\Chkdsk\","NTFS Volume Health Scan","Ready","",""
"SyspartRepair","\Microsoft\Windows\Chkdsk\",,"Ready","%windir%\system32\bcdboot.exe","%windir% /sysrepair"
"License Validation","\Microsoft\Windows\Clip\","Windows Store legacy license migration task","Disabled","%SystemRoot%\system32\ClipUp.exe","-p -s -o"
"CreateObjectTask","\Microsoft\Windows\CloudExperienceHost\",,"Ready","",""
"Consolidator","\Microsoft\Windows\Customer Experience Improvement Program\","If the user has consented to participate in the Windows Customer Experience Improvement Program, this job collects and sends usage data to Microsoft.","Ready","%SystemRoot%\System32\wsqmcons.exe",""
"UsbCeip","\Microsoft\Windows\Customer Experience Improvement Program\","The USB CEIP (Customer Experience Improvement Program) task collects Universal Serial Bus related statistics and information about your machine and sends it to the Windows Device Connectivity engineering group at Microsoft.  The information received is used to help improve the reliability, stability, and overall functionality of USB in Windows.  If the user has not consented to participate in Windows CEIP, this task does not do anything.","Ready","",""
"Data Integrity Scan","\Microsoft\Windows\Data Integrity Scan\","Scans fault-tolerant volumes for latent corruptions","Ready","",""
"Data Integrity Scan for Crash Recovery","\Microsoft\Windows\Data Integrity Scan\","Scans fault-tolerant volumes for fast crash recovery","Ready","",""
"ScheduledDefrag","\Microsoft\Windows\Defrag\","This task optimizes local storage drives.","Ready","%windir%\system32\defrag.exe","-c -h -k -g -$"
"Device","\Microsoft\Windows\Device Information\",,"Ready","%windir%\system32\devicecensus.exe",""
"Metadata Refresh","\Microsoft\Windows\Device Setup\","Performs a device metadata refresh on a periodic basis","Ready","",""
"Scheduled","\Microsoft\Windows\Diagnosis\","The Windows Scheduled Maintenance Task performs periodic maintenance of the computer system by fixing problems automatically or reporting them through Security and Maintenance.","Ready","",""
"DXGIAdapterCache","\Microsoft\Windows\DirectX\",,"Ready","%windir%\system32\dxgiadaptercache.exe",""
"SilentCleanup","\Microsoft\Windows\DiskCleanup\","Maintenance task used by the system to launch a silent auto disk cleanup when running low on free disk space.","Ready","%windir%\system32\cleanmgr.exe","/autoclean /d %systemdrive%"
"Microsoft-Windows-DiskDiagnosticDataCollector","\Microsoft\Windows\DiskDiagnostic\","The Windows Disk Diagnostic reports general disk and system information to Microsoft for users participating in the Customer Experience Program.","Ready","%windir%\system32\rundll32.exe","dfdts.dll,DfdGetDefaultPolicyAndSMART"
"Microsoft-Windows-DiskDiagnosticResolver","\Microsoft\Windows\DiskDiagnostic\","The Microsoft-Windows-DiskDiagnosticResolver warns users about faults reported by hard disks that support the Self Monitoring and Reporting Technology (S.M.A.R.T.) standard. This task is triggered automatically by the Diagnostic Policy Service when a S.M.A.R.T. fault is detected.","Disabled","%windir%\system32\DFDWiz.exe",""
"Diagnostics","\Microsoft\Windows\DiskFootprint\",,"Ready","%windir%\system32\disksnapshot.exe","-z"
"StorageSense","\Microsoft\Windows\DiskFootprint\",,"Ready","",""
"EDP App Launch Task","\Microsoft\Windows\EDP\",,"Ready","",""
"EDP Auth Task","\Microsoft\Windows\EDP\",,"Ready","",""
"EDP Inaccessible Credentials Task","\Microsoft\Windows\EDP\",,"Ready","",""
"StorageCardEncryption Task","\Microsoft\Windows\EDP\",,"Ready","",""
"ExploitGuard MDM policy Refresh","\Microsoft\Windows\ExploitGuard\","Task for applying changes to the machine's Exploit Protection settings.","Ready","",""
"Property Definition Sync","\Microsoft\Windows\File Classification Infrastructure\","Synchronizes the File Classification Infrastructure taxonomy on the computer with the resource property definitions stored in Active Directory Domain Services.","Disabled","",""
"ReconcileFeatures","\Microsoft\Windows\Flighting\FeatureConfig\","Task periodically reconciling feature configurations","Ready","",""
"RefreshCache","\Microsoft\Windows\Flighting\OneSettings\","Task periodically refreshing data for OneSettings clients.","Ready","",""
"ScanForUpdates","\Microsoft\Windows\InstallService\",,"Ready","",""
"ScanForUpdatesAsUser","\Microsoft\Windows\InstallService\",,"Ready","",""
"SmartRetry","\Microsoft\Windows\InstallService\",,"Ready","",""
"WakeUpAndContinueUpdates","\Microsoft\Windows\InstallService\",,"Disabled","",""
"WakeUpAndScanForUpdates","\Microsoft\Windows\InstallService\",,"Disabled","",""
"Installation","\Microsoft\Windows\LanguageComponentsInstaller\","Install language components that match the user's language list.","Ready","",""
"Uninstallation","\Microsoft\Windows\LanguageComponentsInstaller\","Uninstall language components that are not in any user's language list.","Disabled","",""
"TempSignedLicenseExchange","\Microsoft\Windows\License Manager\","Exchanges temporary preinstalled licenses for Windows Store licenses.","Ready","",""
"Notifications","\Microsoft\Windows\Location\","Location Notification","Ready","%windir%\System32\LocationNotificationWindows.exe",""
"WindowsActionDialog","\Microsoft\Windows\Location\","Location Notification","Ready","%windir%\System32\WindowsActionDialog.exe",""
"WinSAT","\Microsoft\Windows\Maintenance\","Measures a system's performance and capabilities","Ready","",""
"MapsToastTask","\Microsoft\Windows\Maps\","This task shows various Map related toasts","Ready","",""
"MapsUpdateTask","\Microsoft\Windows\Maps\","This task checks for updates to maps which you have downloaded for offline use. Disabling this task will prevent Windows from notifying you of updated maps.","Disabled","",""
"ProcessMemoryDiagnosticEvents","\Microsoft\Windows\MemoryDiagnostic\","Schedules a memory diagnostic in response to system events.","Disabled","",""
"RunFullMemoryDiagnostic","\Microsoft\Windows\MemoryDiagnostic\","Detects and mitigates problems in physical memory (RAM).","Disabled","",""
"MNO Metadata Parser","\Microsoft\Windows\Mobile Broadband Accounts\","Mobile Broadband Account Experience Metadata Parser","Ready","%SystemRoot%\System32\MbaeParserTask.exe",""
"LPRemove","\Microsoft\Windows\MUI\","Launch language cleanup tool","Ready","%windir%\system32\lpremove.exe",""
"SystemSoundsService","\Microsoft\Windows\Multimedia\","System Sounds User Mode Agent","Disabled","",""
"GatherNetworkInfo","\Microsoft\Windows\NetTrace\","Network information collector","Ready","%windir%\system32\gatherNetworkInfo.vbs",""
"SDN Diagnostics Task","\Microsoft\Windows\Network Controller\","This task manages SDN diagnostics logs.","Disabled","%windir%\System32\SDNDiagnosticsTask.exe",""
"Background Synchronization","\Microsoft\Windows\Offline Files\","This task controls periodic background synchronization of Offline Files when the user is working in an offline mode.","Disabled","",""
"Logon Synchronization","\Microsoft\Windows\Offline Files\","This task initiates synchronization of Offline Files when a user logs onto the system.","Disabled","",""
"Secure-Boot-Update","\Microsoft\Windows\PI\","This task updates the Secure Boot variables.","Ready","",""
"Sqm-Tasks","\Microsoft\Windows\PI\","This task gathers information about the Trusted Platform Module (TPM), Secure Boot, and Measured Boot.","Ready","",""
"Server Manager Performance Monitor","\Microsoft\Windows\PLA\",,"Disabled","%systemroot%\system32\rundll32.exe","%systemroot%\system32\pla.dll,PlaHost ""Server Manager Performance Monitor"" ""$(Arg0)"""
"Device Install Group Policy","\Microsoft\Windows\Plug and Play\","Device Installation Group Policy Change Handler","Ready","",""
"Device Install Reboot Required","\Microsoft\Windows\Plug and Play\","Notifies the user that Windows needs to be restarted to finish setting up a device.","Ready","",""
"Sysprep Generalize Drivers","\Microsoft\Windows\Plug and Play\","Generalize driver state in order to prepare the system to be bootable on any hardware configuration.","Ready","%SystemRoot%\System32\drvinst.exe","6"
"AnalyzeSystem","\Microsoft\Windows\Power Efficiency Diagnostics\","This task analyzes the system looking for conditions that may cause high energy use.","Ready","",""
"LoginCheck","\Microsoft\Windows\PushToInstall\",,"Disabled","%windir%\system32\sc.exe","start pushtoinstall login"
"Registration","\Microsoft\Windows\PushToInstall\",,"Ready","%windir%\system32\sc.exe","start pushtoinstall registration"
"MobilityManager","\Microsoft\Windows\Ras\","Provides support for the switching of mobility enabled VPN connections if their underlying interface goes down.","Ready","",""
"VerifyWinRE","\Microsoft\Windows\RecoveryEnvironment\","Validates the Windows Recovery Environment.","Disabled","",""
"RegIdleBackup","\Microsoft\Windows\Registry\","Registry Idle Backup Task","Ready","",""
"CleanupOldPerfLogs","\Microsoft\Windows\Server Manager\",,"Ready","%systemroot%\system32\cscript.exe","/B /nologo %systemroot%\system32\calluxxprovider.vbs $(Arg0) $(Arg1) $(Arg2)"
"ServerManager","\Microsoft\Windows\Server Manager\","Task for launching Initial Configuration Tasks or Server Manager at logon.","Ready","%windir%\system32\ServerManagerLauncher.exe",""
"StartComponentCleanup","\Microsoft\Windows\Servicing\",,"Ready","",""
"Account Cleanup","\Microsoft\Windows\SharedPC\",,"Disabled","%windir%\System32\rundll32.exe","%windir%\System32\Windows.SharedPC.AccountManager.dll,StartMaintenance"
"CreateObjectTask","\Microsoft\Windows\Shell\","Provides support for shell components that access system data","Ready","",""
"IndexerAutomaticMaintenance","\Microsoft\Windows\Shell\","Keeps the search index up to date","Ready","",""
"Collection","\Microsoft\Windows\Software Inventory Logging\",,"Disabled","%systemroot%\system32\cmd.exe","/d /c %systemroot%\system32\silcollector.cmd publish"
"Configuration","\Microsoft\Windows\Software Inventory Logging\",,"Ready","%systemroot%\system32\cmd.exe","/d /c %systemroot%\system32\silcollector.cmd configure"
"SvcRestartTask","\Microsoft\Windows\SoftwareProtectionPlatform\","This task restarts the Software Protection Platform service at the specified time","Ready","",""
"SvcRestartTaskLogon","\Microsoft\Windows\SoftwareProtectionPlatform\","This task restarts the Software Protection Platform service when user logon occurs","Disabled","",""
"SvcRestartTaskNetwork","\Microsoft\Windows\SoftwareProtectionPlatform\","This task restarts the Software Protection Platform service when a new network is detected","Disabled","",""
"SpaceAgentTask","\Microsoft\Windows\SpacePort\","Storage Spaces Settings","Ready","%windir%\system32\SpaceAgent.exe",""
"SpaceManagerTask","\Microsoft\Windows\SpacePort\","$(@%SystemRoot%\system32\spaceman.exe,-3)","Ready","%windir%\system32\spaceman.exe","/Work"
"HeadsetButtonPress","\Microsoft\Windows\Speech\",,"Ready","%windir%\system32\speech_onecore\common\SpeechRuntime.exe","StartedFromTask"
"SpeechModelDownloadTask","\Microsoft\Windows\Speech\",,"Ready","%windir%\system32\speech_onecore\common\SpeechModelDownload.exe",""
"Storage Tiers Management Initialization","\Microsoft\Windows\Storage Tiers Management\","Initializes the Storage Tiers Management service when the first tiered storage space is detected on the system. Do not remove or modify this task.","Ready","",""
"Storage Tiers Optimization","\Microsoft\Windows\Storage Tiers Management\","Optimizes the placement of data in storage tiers on all tiered storage spaces in the system.","Disabled","%windir%\system32\defrag.exe","-c -h -g -# -m 8 -i 13500"
"Interactive","\Microsoft\Windows\Task Manager\","Runs a task as the interactive user.","Ready","",""
"MsCtfMonitor","\Microsoft\Windows\TextServicesFramework\","TextServicesFramework monitor task","Ready","",""
"ForceSynchronizeTime","\Microsoft\Windows\Time Synchronization\","This task performs time synchronization.","Ready","",""
"SynchronizeTime","\Microsoft\Windows\Time Synchronization\","Maintains date and time synchronization on all clients and servers in the network. If this service is stopped, date and time synchronization will be unavailable. If this service is disabled, any services that explicitly depend on it will fail to start.","Ready","%windir%\system32\sc.exe","start w32time task_started"
"SynchronizeTimeZone","\Microsoft\Windows\Time Zone\","Updates timezone information. If this task is stopped, local time may not be accurate for some time zones.","Ready","%windir%\system32\tzsync.exe",""
"Tpm-HASCertRetr","\Microsoft\Windows\TPM\","This task requests a Health Attestation Certificate.","Ready","",""
"Tpm-Maintenance","\Microsoft\Windows\TPM\","This task supports the Trusted Platform Module (TPM) by performing background actions on behalf of the OS.","Ready","",""
"Backup Scan","\Microsoft\Windows\UpdateOrchestrator\",,"Ready","%systemroot%\system32\usoclient.exe","StartScan"
"MusUx_UpdateInterval","\Microsoft\Windows\UpdateOrchestrator\",,"Ready","%systemroot%\system32\MusNotification.exe","LogonDisplay"
"Schedule Scan","\Microsoft\Windows\UpdateOrchestrator\",,"Ready","%systemroot%\system32\usoclient.exe","StartScan"
"Schedule Scan Static Task","\Microsoft\Windows\UpdateOrchestrator\","This task performs a scheduled Windows Update scan.","Ready","%systemroot%\system32\usoclient.exe","StartScan"
"USO_UxBroker","\Microsoft\Windows\UpdateOrchestrator\","This task triggers a system reboot following update installation.","Ready","%systemroot%\system32\MusNotification.exe",""
"UPnPHostConfig","\Microsoft\Windows\UPnP\","Set UPnPHost service to Auto-Start","Ready","sc.exe","config upnphost start= auto"
"HiveUploadTask","\Microsoft\Windows\User Profile Service\","This task will automatically upload a roaming user profile's registry hive to its network location.","Disabled","",""
"PerformRemediation","\Microsoft\Windows\WaaSMedic\","Helps recover update-related services to the supported configuration.","Disabled","",""
"ResolutionHost","\Microsoft\Windows\WDI\","The Windows Diagnostic Infrastructure Resolution host enables interactive resolutions for system problems detected by the Diagnostic Policy Service. It is triggered when necessary by the Diagnostic Policy Service in the appropriate user session. If the Diagnostic Policy Service is not running, the task will not run","Running","",""
"Windows Defender Cache Maintenance","\Microsoft\Windows\Windows Defender\","Periodic maintenance task.","Ready","C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23090.2008-0\MpCmdRun.exe","-IdleTask -TaskName WdCacheMaintenance"
"Windows Defender Cleanup","\Microsoft\Windows\Windows Defender\","Periodic cleanup task.","Ready","C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23090.2008-0\MpCmdRun.exe","-IdleTask -TaskName WdCleanup"
"Windows Defender Scheduled Scan","\Microsoft\Windows\Windows Defender\","Periodic scan task.","Ready","C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23090.2008-0\MpCmdRun.exe","Scan -ScheduleJob -ScanTrigger 55 -IdleScheduledJob"
"Windows Defender Verification","\Microsoft\Windows\Windows Defender\","Periodic verification task.","Ready","C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23090.2008-0\MpCmdRun.exe","-IdleTask -TaskName WdVerification"
"QueueReporting","\Microsoft\Windows\Windows Error Reporting\","Windows Error Reporting task to process queued reports.","Ready","%windir%\system32\wermgr.exe","-upload"
"BfeOnServiceStartTypeChange","\Microsoft\Windows\Windows Filtering Platform\","This task adjusts the start type for firewall-triggered services when the start type of the Base Filtering Engine (BFE) is disabled.","Ready","%windir%\system32\rundll32.exe","bfe.dll,BfeOnServiceStartTypeChange"
"UpdateLibrary","\Microsoft\Windows\Windows Media Sharing\","This task updates the cached list of folders and the security permissions on any new files in a user?s shared media library.","Ready","""%ProgramFiles%\Windows Media Player\wmpnscfg.exe""",""
"Calibration Loader","\Microsoft\Windows\WindowsColorSystem\","This task applies color calibration settings.","Ready","",""
"Scheduled Start","\Microsoft\Windows\WindowsUpdate\","This task is used to start the Windows Update service when needed to perform scheduled operations such as scans.","Ready","C:\Windows\system32\sc.exe","start wuauserv"
"CacheTask","\Microsoft\Windows\Wininet\","Wininet Cache Task","Running","",""
"Automatic-Device-Join","\Microsoft\Windows\Workplace Join\","Register this computer if the computer is already joined to an Active Directory domain.","Ready","%SystemRoot%\System32\dsregcmd.exe","$(Arg0) $(Arg1) $(Arg2)"
"Recovery-Check","\Microsoft\Windows\Workplace Join\","Performs recovery check.","Disabled","%SystemRoot%\System32\dsregcmd.exe","/checkrecovery"
"Firefox Background Update 308046B0AF4A39CB","\Mozilla\","The Background Update task checks for updates to Firefox when Firefox is not running. This task is installed automatically by Firefox, and is reinstalled when Firefox runs. To disable this task, update the browser settings or the Firefox enterprise policy setting ?BackgroundAppUpdate?.","Ready","C:\Program Files\Mozilla Firefox\firefox.exe","--MOZ_LOG sync,prependheader,timestamp,append,maxsize:1,Dump:5 --MOZ_LOG_FILE C:\ProgramData\Mozilla-1de4eec8-1241-4177-a864-e594e8d1fb38\updates\308046B0AF4A39CB\backgroundupdate.moz_log --backgroundtask backgroundupdate"
"@

# Define the output path
$outputPath = Join-Path -Path ([Environment]::GetFolderPath("MyDocuments")) -ChildPath "validTaskScheduler.csv"

# Write the text to the CSV file
$text | Out-File -FilePath $outputPath